### PR TITLE
Add javascripthon

### PR DESCRIPTION
**Pull request by icarito**
:-)

### CODE REVIEW

**Comment by icarito** [comment]
This is giving me some issues as it seems I need to parse stderr too, or it could freeze.
Working on it.

**Comment by icarito** [comment]
This seems to work ok.

**Comment by icarito** [comment]
I'd still miss a good error message when `pj` is not installed...

**Comment by icarito** [comment]
Hi, now I'm proud ;-)
I'm using this with vue-loader to make python vue.js web components :-D

**Comment by icarito** [comment]
(Sorry for the spam!)

**Comment by martim00** [comment]
Wow, great job! I didn't know about javascripthon. Very impressive framework. I'll test asap.
Also, let me ask. How do you manage to get vue-loader work with this? Do you mind in putting an example in the /example folder?

**Comment by icarito** [comment]
Excited to be of help. *Obrigado* for the project.
I am able to make Vue-components like below. The syntax vue wants is not great, looking for a better style:
```python
<script lang="py?compiler=pj">

class Component:
    def __init__(self):
        self['data'] = lambda: { 'test': 2 }
        self['components'] = { 
                      'AppLogo':require('~/components/AppLogo.vue')['default'] }
        self['computed'] = { 'data': lambda: 2 }


module.exports = Component()

</script>
```

I am using the `nuxt.js` framework.

**Comment by icarito** [comment]
Here's another attempt with nicer syntax thanks to `vue-class-component`:
```python
<script lang="py?compiler=pj">

Vue = require('vue')['default']
component = require('vue-class-component')['default']

@component
class MyIndex(Vue):

    def __init__(self):
        super().__init__()
        self['components'] = { 'AppLogo':require('~/components/AppLogo.vue')['default'] }
        self['data'] = self.data

    def data(self):
        return { 'test': 2 }

    @property
    def my_value(self):
        return 3

module.exports = MyIndex()

</script>
```

**Comment by martim00** [comment]
Cool, very interesting approach! I will experiment with this.

**Pull request merged**
